#  Data sheet

#  All race number values are integers entered as (lower, upper) range
#  Add adult height, weight, and size
#  Add names from name generators (pull data from web) (from Halfling)
#  Change age, height, and weight to ranges (4 fields)

races = {
    'Dwarf': {
        'names': {
            'male': [
                'Addanc',
                'Ari',
                'Bhalkyl',
                'Aigror',
                'Dramola',
                'Dori',
                'Galvon',
                'Gandalf',
                'Gloin',
                'Braka',
                'Duvur',
                'Bes',
                'Cola',
                'Malgon Keghood',
                'Balthrasir',
                'Sneezy',
                'Ballin',
                'Thovan',
                'Draupin',
                'Argos',
                'Thondin',
                'Bashful',
                'Bavola',
                'Bothor',
                'Dragrola',
                'Grumpy',
                'Firguc Minebrow',
                'Gidel',
                'Bhalmun',
                'Avion',
                'Dopey',
                'Kibil',
                'Divira',
                'Danil',
                'Calgak',
                'Algir',
                'Brokk',
                'Wade',
                'Bagrna',
                'Ruvon',
                'Hannar',
                'Chirysaor',
                'Happy',
                'Artion',
                'Baglia',
                'Daremrun Deepgrip',
                'Bombur',
                'Ebdrus',
                'Buboth Flintcoat',
                'Anin',
                'Dothura',
                'Brand',
                'Bovan',
                'Goliath',
                'Bharrom',
                'Dwomnaed Runebreaker',
                'Dogrila',
                'Onfroi',
                'Oin',
                'Davan',
                'Bargun',
                'Khubrorlug Anvilbender',
                'Chalona',
                'Kili',
                'Bofur',
                'Doulgarlig Anvilmaster',
                'Dondna',
                'Huffie',
                'Fimbul',
                'Digan',
                'Bilbur',
                'Bifur',
                'Glorgil',
                'Nori',
                'Anvari',
                'Calgrima',
                'Malvon',
                'Titan',
                'Gim',
                'Bamira',
                'Anil',
                'Bramdur'],
            'female': [
                'Bari',
                'Dila',
                'Thovir',
                'Crystal',
                'Dunora',
                'Gagon',
                'Dhara',
                'Dolana',
                'Agran',
                'Aden',
                'Bhelkam',
                'Esmeralda',
                'Calona',
                'Demeter',
                'Dradir',
                'Bramdahr',
                'Thovir',
                'Erla',
                'Admina',
                'Giva',
                'Dodur',
                'Brynjolvur',
                'Rundir',
                'Sienna',
                'Jade',
                'Chalia',
                'Dilgli',
                'Branmand',
                'Randon',
                'Dovana',
                'Ebgran',
                'Flintheart',
                'Bofar',
                'Gimli',
                'Dellinger',
                'Dithin',
                'Dora',
                'Givur',
                'Lazuli',
                'Cosette',
                'Dugrona',
                'Thortor',
                'Calgrima',
                'Ela',
                'Amethyst',
                'Gavil',
                'Eiki',
                'Fiden',
                'Dravan',
                'Lana Axe',
                'Chalia',
                'Elindur',
                'Eartha',
                'Avil',
                'Reginn',
                'Edmundur',
                'Rudli',
                'Montana',
                'Eilivur',
                'Sapphire',
                'Barol',
                'Calund',
                'Emorette',
                'Malvan',
                'Ula',
                'Dorola',
                'Dovli',
                'Afra',
                'Bjarki',
                'Narvi',
                'Bavol',
                'Rarona']
        },
        'Child Age': (range(10, 50)),
        'Adult Age': (range(50, 350)),
        'Height': (range(4, 5)),  # measured in feet
        'Weight': (range(125, 200)),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Darkvision', 'Dwarven Resilience', 'Stonecunning'],
        'Languages': ['Common', 'Dwarvish'],
        'Subrace': ['Hill Dwarf', 'Mountain Dwarf']
    },
    'Elf': {
        'names': {
            'male': [
                'Chathangla',
                'Cheyrt',
                'Chozzaste',
                'Chylnot',
                'Cluhurac',
                'Cluy',
                'Cohna',
                'Conal',
                'Conna',
                'Cornait',
                'Cory',
                'Cymbii',
                'Cysten',
                'Dalyo',
                'Dakat',
                'Drot',
                'Druinda',
                'Durla',
                'Durothi',
                'Dyffro',
                'Earynspiei',
                'Elandor',
                'Elanja',
                'Elasho',
                'Elbauthi',
                'Elberet',
                'Elidy',
                'Elio',
                'Elkhaze',
                'Ellisa',
                'Elorfinda',
                'Elorshi',
                'Erla',
                'Erlatha',
                'Eroa',
                'Erolit',
                'Eschallu',
                'Estela',
                'Faahres',
                'Faela',
                'Faely',
                'Faerandui',
                'Falae',
                'Faoraa',
                'Felaer',
                'Fenia',
                'Filvendo',
                'Filvere',
                'Finufaranel',
                'Jhaartae',
                'Jhaero',
                'Jhara',
                'Jhary',
                'Jhuvi',
                'Kalaered',
                'Kata',
                'Katy',
                'Kelethery',
                'Kelvha',
                'Kende',
                'Kery',
                'Keryt',
                'Kesefeho',
                'Khaalindaa',
                'Khari',
                'Khata',
                'Kiyuig',
                'Klaer',
                'Kolva',
                'Korrigas',
                'Krolot',
                'Kuorno',
                'Kusky',
                'Kusky',
                'Kymi'
                'Nhamasha',
                'Nieve',
                'Nindro',
                'Ninthalo',
                'Nlossa',
                'Quastart',
                'Quyn',
                'Raeranthu',
                'Raiby',
                'Ralikantha',
                'Ralno',
                'Rhangy',
                'Rhenalyr',
                'Rhespe',
                'Rhiste',
                'Rhothomi',
                'Rhy',
                'Rilita',
                'Riluanet',
                'Roli',
                'Rothelo',
                'Rothilio',
                'Ruard',
                'Rueha',
                'Ruit',
                'Rumathi',
                'Ruvae',
                'Ruve',
                'Ruvy',
                'Rychel',
                'Ryfo',
                'Ryu',
                'Ryvvik',
                'Sadalym',
                'Saeve',
                'Sakrattar',
                'Sambla',
                'Sandev',
                'Seancha',
                'Seit',
                'Selanla',
                'Selgaut',
                'Shae',
                'Shammat',
                'Sharia',
                'Sharlari',
                'Shaundy',
                'Shevaras',
                'Shonassi',
                'Shyrri',
                'Siiris',
                'Silvy',
                'Simima',
                'Sinah',
                'Skalani',
                'Sonta',
                'Tarathie',
                'Tared',
                'Tarosspu',
                'Tarro',
                'Tasa',
                'Tassario',
                'Tathal',
                'Tehlma',
                'Teiris',
                'Tenyaj',
                'Tethi',
                'Thalani',
                'Thalla',
                'Thatory',
                'Thiiltha',
                'Thurda',
                'Thurruvy',
                'Tiarshu',
                'Tlannata',
                'Tolth',
                'Tordynna',
                'Toros',
                'Traelior',
                'Travara',
                'Trianda',
                'Triktappi',
                'Tsae',
                'Tsiilma'
            ],
            'female': [
                'Gwynnestri',
                'Gylledh',
                'Haalij',
                'Hacathr',
                'Halaem',
                'Halam',
                'Halaem',
                'Halanaestr',
                'Hamaliti',
                'Haramar',
                'Helarth',
                'Hhor',
                'Holon',
                'Huquetha',
                'Hyci',
                'Iahala',
                'Ialanth',
                'Ikeshi',
                'Ildilyntr',
                'Ilmadi',
                'Ilyran',
                'Ilythyrr',
                'Imdalac',
                'Imizae',
                'Immianth',
                'Imr',
                'Imramarthre',
                'Imryl',
                'Innovindi',
                'Ioelen',
                'Irhaa',
                'Isciir',
                'Ithrythr',
                'Itiirea',
                'Itylr',
                'Jastr',
                'Jeardr',
                'Jhae',
                'Jhalas',
                'Jhanandr',
                'Jhaumrith',
                'Jhiilsra',
                'Ilseve',
                'Ilyran',
                'Immianth',
                'Isilfarre',
                'Kavral',
                'Kayless',
                'Keerl',
                'Keishar',
                'Kethrylli',
                'Key',
                'Khiipaer',
                'Kileonthea',
                'Kythael',
                'Laamtor',
                'Laerdy',
                'Laerun',
                'Laurlaethe',
                'Lazzia',
                'Leilath',
                'Lilut',
                'Llamry',
                'Lorele',
                'Lydi’aleer',
                'Lyraese',
                'Maaleshiir',
                'Maelyrr',
                'Maeraly',
                'Mait',
                'Makael',
                'Malruthii',
                'Marion',
                'Mariss',
                'Martain',
                'Meir',
                'Melaru',
                'Merethy',
                'Merialet',
                'Merie',
                'Merlar',
                'Mistal',
                'Mladri',
                'Mnuva',
                'Morgwai',
                'Morygga',
                'Muerlar',
                'Mylael',
                'Mylaerl',
                'Myrian',
                'Naevy',
                'Nakiash',
                'Nambr',
                'Namyriith',
                'Nanalethale',
                'Nanthe',
                'Nanthleen',
                'Naumy',
                'Nlae',
                'Nual',
                'Nuelet',
                'Nuovi',
                'Nushal',
                'Nylaathri',
                'Ochyllys',
                'Oluevaer',
                'Phaer',
                'Phantyn',
                'Phelorn',
                'Phuingar',
                'Phyrr',
                'Polla',
                'Puorlaa',
                'Qemb',
                'Quamar',
                'Raejiis',
                'Raeraunth',
                'Rathiai',
                'Renestra',
                'Roanmar',
                'Ruavi',
                'Rubra',
                'Rylla',
                'Saelih',
                'Saélih',
                'Said',
                'Sakaal',
                'Sariand',
                'Sary',
                'Schima',
                'Seiry',
                'Seldann',
                'Seluss',
                'Séonai',
                'Shae',
                'Shadowmoo',
                'Shalan',
                'Shalanth',
                'Shalendr',
                'Shalheir',
                'Shandala',
                'Shanyrri',
                'Sharaer',
                'Sheedr',
                'Sheer',
                'Shialaeva',
                'Shi’larr'
            ]
        },
        'Child Age': (10, 100),
        'Adult Age': (100, 700),
        'Height': (5, 6),  # measured in feet
        'Weight': (100, 150),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Darkvision', 'Keen Senses', 'Fey Ancestry', 'Trance'],
        'Languages': ['Common', 'Elvish'],
        'Subrace': ['High Elf', 'Wood Elf', 'Dark Elf (Drow)']
    },
    'Halfling': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (10, 20),
        'Adult Age': (20, 150),
        'Height': (2.5, 3.5),  # measured in feet
        'Weight': (30, 50),  # measured in pounds
        'Size': 'Small',
        'Features': ['Lucky', 'Brave', 'Nimbleness'],
        'Languages': ['Common', 'Halfling'],
        'Subrace': ['Lightfoot', 'Stout']
    },
    'Human': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (8, 18),
        'Adult Age': (21, 100),
        'Height': (5, 7),  # measured in feet
        'Weight': (125, 200),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Versatility'],
        'Languages': ['Common'],
        'Subrace': ['Calishite', 'Chondathan', 'Damaran', 'Illuskan', 'Mulan', 'Rashemi', 'Shou', 'Turami']
    },
    'Dragonborn': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (4, 15),
        'Adult Age': (20, 80),
        'Height': (6.5, 7.5),  # measured in feet
        'Weight': (200, 300),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Draconic Ancestry', 'Breath Weapon', 'Damage Resistance'],
        'Languages': ['Common', 'Draconic'],
        'Subrace': ['Black -- Acid', 'Blue -- Lightening', 'Brass -- Fire', 'Bronze -- Lightening', 'Copper -- Acid',
                    'Gold -- Fire', 'Green -- Poison', 'Red -- Fire', 'Silver -- Cold', 'White -- Cold']
    },
    'Gnome': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (8, 40),
        'Adult Age': (40, 450),
        'Height': (3, 4),  # measured in feet
        'Weight': (30, 50),  # measured in pounds
        'Size': 'Small',
        'Features': ['Gnome Cunning', 'Speak with Small Beasts', 'Tinker'],
        'Languages': ['Common', 'Gnomish'],
        'Subrace': ['Rock Gnome', 'Forest Gnome']
    },
    'Half-Elf': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (6, 20),
        'Adult Age': (21, 200),
        'Height': (5, 7),  # measured in feet
        'Weight': (125, 200),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Darkvision', 'Fey Ancestry', 'Skill Versatility'],
        'Languages': ['Common', 'Elvish'],
        'Subrace': ['Half human - Half elf']
    },
    'Half-Orc': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (6, 14),
        'Adult Age': (14, 75),
        'Height': (5, 7),  # measured in feet
        'Weight': (125, 200),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Darkvision', 'Relentless Endurance', 'Savage Attack'],
        'Languages': ['Common', 'Orc'],
        'Subrace': ['Half human - Half orc']
    },
    'Tiefling': {
        'names': {
            'male': ['a'],
            'female': ['b']
        },
        'Child Age': (6, 21),
        'Adult Age': (21, 130),
        'Height': (5, 7),  # measured in feet
        'Weight': (125, 200),  # measured in pounds
        'Size': 'Medium',
        'Features': ['Darkvision', 'Hellish Resistance', 'Infernal Legacy'],
        'Languages': ['Common', 'Infernal'],
        'Subrace': ['Asmodeus', 'Baalzebul', 'Dispater', 'Fierna', 'Glasya', 'Levistus', 'Mammon', 'Zariel']
    },
}

distinct_ft = {
    'Jewellery': ['a'],
    'Clothing': ['b'],
    'Tattoo': ['c'],
    'Body Ft': ['d']
}

hi_ability = ['STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA']

lo_ability = ['STR', 'DEX', 'CON', 'INT', 'WIS', 'CHA']

talent = ['a']

mannerism = ['b']

interaction_style = ['c']

ideal = ['d']

bond = ['e']

flaw = ['f']
